[project]
name = "salary-aggregation"
version = "0.1.0"
description = ""
authors = [
    {name = "Nikolay Korkushko",email = "nikolaykorkushko@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.118.2,<0.119.0)",
    "uvicorn (>=0.37.0,<0.38.0)",
    "pymongo (>=4.15.3,<5.0.0)",
    "aiogram (>=3.22.0,<4.0.0)",
    "motor (>=3.7.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
black = "^25.9.0"
mypy = "^1.18.2"
flake8 = "^7.3.0"
isort = "^7.0.0"

